[package]
name = "rock-paper-scissors"
version = "0.1.0"
authors = ["Oasis Labs <feedback@oasislabs.com>"]
edition = "2018"
publish = false

[dependencies]
oasis-std = "0.4"

[dev-dependencies]
oasis-test = "0.4"
